function corrected_img = smoothTV(img, gradient_threshold)
  % .055 seems to be a typical gradient threshold
  corrected_img = imdiffusefilt(abs(img), ...
    'ConductionMethod', 'exponential', ...
    'GradientThreshold', gradient_threshold, ...
    'NumberOfIterations', 5); % Fixed number of iterations
end 